apiVersion: apps/v1
kind: Pod
metadata: 
    name: web-app
    labels:
        app: web-app
spec:
    containers:
    -  name: demo-kube
       image: docker.io/demo-kube:latest
       ports:
          containerPort: 80
 
