apiVersion: apps/v1
kind: Deployment
metadata: 
    name: web-app
spec:
    selector:
        matchLabels:
          app: web
      replicas: 2 
      template:
        metadata:
          labels:
            app: web
        spec:
          containers:
          - name: kube-demo
            image: docker.io/vishnusk/kube-demo:latest
            ports:
            - containerPort: 80
